spring:
  application:
    name: exchange-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exchange_service?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show_sql: true

server:
  port: 8000


